import type { Argv } from "yargs"
import { UI } from "../ui"
import * as prompts from "@clack/prompts"
import { $ } from "bun"
import fs from "fs"
import path from "path"

type DevRepo = {
  root: string
  packageDir: string
  buildScript: string
}

type FindDevRepoInput = {
  explicitPath?: string
  startPath?: string
  execPath?: string
}

function normalizePath(input: string) {
  const resolved = path.resolve(input)
  try {
    return fs.realpathSync(resolved)
  } catch {
    return resolved
  }
}

function isFile(input: string) {
  try {
    return fs.statSync(input).isFile()
  } catch {
    return false
  }
}

function resolveRepo(candidate: string): DevRepo | undefined {
  const fromRootScript = path.join(candidate, "packages", "opencode", "script", "build.ts")
  if (fs.existsSync(fromRootScript)) {
    const root = normalizePath(candidate)
    return {
      root,
      packageDir: path.join(root, "packages", "opencode"),
      buildScript: fromRootScript,
    }
  }

  const packageDirScript = path.join(candidate, "script", "build.ts")
  if (
    fs.existsSync(packageDirScript) &&
    path.basename(candidate) === "opencode" &&
    path.basename(path.dirname(candidate)) === "packages"
  ) {
    const packageDir = normalizePath(candidate)
    return {
      root: path.resolve(packageDir, "..", ".."),
      packageDir,
      buildScript: packageDirScript,
    }
  }

  return undefined
}

function parentDirs(start: string) {
  const values: string[] = []
  let current = normalizePath(start)
  while (true) {
    values.push(current)
    const parent = path.dirname(current)
    if (parent === current) break
    current = parent
  }
  return values
}

export function findDevRepo(input: FindDevRepoInput = {}): DevRepo | undefined {
  const seeds = [input.explicitPath, input.startPath, input.execPath].filter((value): value is string => !!value)
  const seen = new Set<string>()
  const candidates: string[] = []

  for (const seed of seeds) {
    const normalizedSeed = normalizePath(seed)
    const start = isFile(normalizedSeed) ? path.dirname(normalizedSeed) : normalizedSeed
    for (const dir of parentDirs(start)) {
      if (seen.has(dir)) continue
      seen.add(dir)
      candidates.push(dir)
    }
  }

  for (const candidate of candidates) {
    const repo = resolveRepo(candidate)
    if (repo) return repo
  }

  return undefined
}

export function buildDevUpdateArgs(keepBuildArtifacts = false) {
  const args = ["--single", "--skip-install"]
  if (keepBuildArtifacts) args.push("--keep-bun-build")
  return args
}

export const DevUpdateCommand = {
  command: "dev-update",
  describe: "rebuild local opencontext binary from source checkout",
  builder: (yargs: Argv) =>
    yargs
      .option("path", {
        alias: "p",
        type: "string",
        describe: "path to local opencontext repo root or packages/opencode directory",
      })
      .option("keep-build-artifacts", {
        type: "boolean",
        default: false,
        describe: "keep intermediate .bun-build artifacts generated by bun build",
      }),
  handler: async (args: { path?: string; keepBuildArtifacts?: boolean }) => {
    UI.empty()
    UI.println(UI.logo("  "))
    UI.empty()
    prompts.intro("Dev Update")

    const repo = findDevRepo({
      explicitPath: args.path,
      startPath: process.cwd(),
      execPath: process.execPath,
    })

    if (!repo) {
      prompts.log.error("Could not find a local opencontext source checkout.")
      prompts.log.info("Run this inside the repo, pass --path, or use `opencontext upgrade` for package installs.")
      prompts.outro("Done")
      return
    }

    prompts.log.info(`Repo: ${repo.root}`)
    const beforeVersion = (await $`${process.execPath} --version`.nothrow().quiet().text()).trim()
    const gitHead = (await $`git -C ${repo.root} rev-parse --short HEAD`.nothrow().quiet().text()).trim()
    const gitDirty = (await $`git -C ${repo.root} status --short`.nothrow().quiet().text()).trim()
    if (beforeVersion) prompts.log.info(`Version before: ${beforeVersion}`)
    if (gitHead) prompts.log.info(`Source revision: ${gitHead}${gitDirty ? " (dirty)" : ""}`)

    const spinner = prompts.spinner()
    spinner.start("Building local binary...")

    const buildArgs = buildDevUpdateArgs(Boolean(args.keepBuildArtifacts))
    const build = await $`bun run --cwd ${repo.packageDir} script/build.ts ${buildArgs}`.nothrow().quiet()
    if (build.exitCode !== 0) {
      spinner.stop("Build failed", 1)
      const stderr = build.stderr.toString("utf8").trim()
      const stdout = build.stdout.toString("utf8").trim()
      prompts.log.error(stderr || stdout || `Build exited with code ${build.exitCode}`)
      prompts.outro("Done")
      return
    }

    spinner.stop("Build complete")
    const afterVersion = (await $`${process.execPath} --version`.nothrow().quiet().text()).trim()
    if (beforeVersion && afterVersion) prompts.log.info(`Version after: ${afterVersion} (was ${beforeVersion})`)
    else if (afterVersion) prompts.log.info(`Version after: ${afterVersion}`)
    prompts.log.info("If your shell caches command paths, run `hash -r`.")
    prompts.outro("Done")
  },
}
